version: '3.3'
services:
  servidor1:
    image: contlaravel
    container_name: servidorlaravel
    ports:
      - 8085:80
    volumes:
      - ./laravel/:/var/www/html
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - USUARIO=mohamed
      - PASSWD=Mohamed1.*
      - PROYECTO=EMDE
    networks:
      netbase:
        ipv4_address: 172.120.21.5
networks:
  netbase:
    ipam:
      driver: default
      config:
        - subnet: 172.120.21.0/24
